/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLTN.UI;

import QLTN.Dao.ComputerDao;
import QLTN.Dao.ComputerGroupDao;
import QLTN.Entity.Computer;
import QLTN.Entity.ComputerGroup;
import QLTN.Utils.Masterfrom;
import QLTN.Utils.MessageBoxQLTN;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.math.BigDecimal;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AD
 */
public class ComputersJPanel extends Masterfrom {

    /**
     * Creates new form SanPhamJPanel
     */
    public ComputersJPanel() {
        initComponents();
        init();

        tblMaytinh.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 14));
        tblMaytinh.getTableHeader().setBackground(new Color(24, 71, 133));
        tblMaytinh.getTableHeader().setForeground(new Color(255, 255, 255));

        tblLoaimay.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 14));
        tblLoaimay.getTableHeader().setBackground(new Color(24, 71, 133));
        tblLoaimay.getTableHeader().setForeground(new Color(255, 255, 255));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackgroudFormSP = new javax.swing.JPanel();
        tblPanelMayTinh = new javax.swing.JTabbedPane();
        pnlMaytinh = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMaytinh = new javax.swing.JTable();
        lblTenSP = new javax.swing.JLabel();
        lblGia = new javax.swing.JLabel();
        lblTenSPTKiem = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        lblLoaiSP = new javax.swing.JLabel();
        lblTrangthai = new javax.swing.JLabel();
        txtVitri = new javax.swing.JTextField();
        pnlButton = new javax.swing.JPanel();
        btnThemSP = new javax.swing.JButton();
        btnSuaSP = new javax.swing.JButton();
        btnXoaSP = new javax.swing.JButton();
        btnLammoiSP1 = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnTimkiem = new javax.swing.JButton();
        txtTenMay = new javax.swing.JTextField();
        txtIDmay = new javax.swing.JTextField();
        txtIP = new javax.swing.JTextField();
        lblSoLuong = new javax.swing.JLabel();
        lblThongso = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtThongso = new javax.swing.JTextArea();
        lblTenSP1 = new javax.swing.JLabel();
        txtLoai1 = new javax.swing.JTextField();
        cboTrangThai = new javax.swing.JComboBox<>();
        pnlLoaimay = new javax.swing.JPanel();
        pnlNhapsolieu = new javax.swing.JPanel();
        lblMaNV = new javax.swing.JLabel();
        txtTenloai = new javax.swing.JTextField();
        lblTenloaiSP = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        btnThemLoai = new javax.swing.JButton();
        btnSuaLoai = new javax.swing.JButton();
        btnXoaLoai = new javax.swing.JButton();
        btnLammoiLoai = new javax.swing.JButton();
        lblTenloaiSP1 = new javax.swing.JLabel();
        lblTenloaiSP2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtMota = new javax.swing.JTextArea();
        lblMaNV1 = new javax.swing.JLabel();
        txtIDloaimay = new javax.swing.JTextField();
        cboTrangThai2 = new javax.swing.JComboBox<>();
        pnlDanhMucSP = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblLoaimay = new javax.swing.JTable();

        setBackground(new Color (0, 0, 0, 0));
        setPreferredSize(new java.awt.Dimension(1317, 760));

        pnlBackgroudFormSP.setBackground(new Color (0, 0, 0, 0));

        tblPanelMayTinh.setBackground(new Color (0, 0, 0, 0));
        tblPanelMayTinh.setForeground(new java.awt.Color(102, 0, 51));
        tblPanelMayTinh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        pnlMaytinh.setBackground(new Color (0, 0, 0, 0));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        tblMaytinh.setAutoCreateRowSorter(true);
        tblMaytinh.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblMaytinh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Loại", "Tên máy", "Trạng thái", "Thông số", "IP", "Vị trí"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMaytinh.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblMaytinh.setOpaque(false);
        tblMaytinh.setRowHeight(23);
        tblMaytinh.getTableHeader().setReorderingAllowed(false);
        tblMaytinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMaytinhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMaytinh);

        lblTenSP.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTenSP.setForeground(new Color (16,54,103) );
        lblTenSP.setText("ID");

        lblGia.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblGia.setForeground(new Color (16,54,103) );
        lblGia.setText("Vị trí");

        lblTenSPTKiem.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTenSPTKiem.setForeground(new Color (16,54,103) );
        lblTenSPTKiem.setText("Tên máy");

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimKiem.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(51, 51, 51)));
        txtTimKiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimKiemCaretUpdate(evt);
            }
        });

        lblLoaiSP.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblLoaiSP.setForeground(new Color (16,54,103) );
        lblLoaiSP.setText("Loại ");

        lblTrangthai.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTrangthai.setForeground(new Color (16,54,103) );
        lblTrangthai.setText("Trạng thái ");

        txtVitri.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVitri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVitriActionPerformed(evt);
            }
        });

        pnlButton.setBackground(new Color (0, 0, 0, 0));

        btnThemSP.setBackground(new Color (24, 71, 133));
        btnThemSP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemSP.setForeground(new java.awt.Color(255, 255, 255));
        btnThemSP.setText("Thêm");
        btnThemSP.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnThemSP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThemSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemSPActionPerformed(evt);
            }
        });

        btnSuaSP.setBackground(new Color (24, 71, 133));
        btnSuaSP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSuaSP.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaSP.setText("Sửa");
        btnSuaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaSPActionPerformed(evt);
            }
        });

        btnXoaSP.setBackground(new Color (24, 71, 133));
        btnXoaSP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaSP.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaSP.setText("Xóa");
        btnXoaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaSPActionPerformed(evt);
            }
        });

        btnLammoiSP1.setBackground(new Color (24, 71, 133));
        btnLammoiSP1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLammoiSP1.setForeground(new java.awt.Color(255, 255, 255));
        btnLammoiSP1.setText("Làm mới");
        btnLammoiSP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiSP1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButtonLayout = new javax.swing.GroupLayout(pnlButton);
        pnlButton.setLayout(pnlButtonLayout);
        pnlButtonLayout.setHorizontalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLammoiSP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlButtonLayout.createSequentialGroup()
                        .addGroup(pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnXoaSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(btnSuaSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlButtonLayout.setVerticalGroup(
            pnlButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButtonLayout.createSequentialGroup()
                .addComponent(btnThemSP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSuaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoaSP, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLammoiSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnFirst.setBackground(new Color (24, 71, 133));
        btnFirst.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnFirst.setForeground(new java.awt.Color(255, 255, 255));
        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnPrev.setBackground(new Color (24, 71, 133));
        btnPrev.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPrev.setForeground(new java.awt.Color(255, 255, 255));
        btnPrev.setText("<<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        btnNext.setBackground(new Color (24, 71, 133));
        btnNext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnLast.setBackground(new Color (24, 71, 133));
        btnLast.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLast.setForeground(new java.awt.Color(255, 255, 255));
        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnTimkiem.setBackground(new Color (24, 71, 133));
        btnTimkiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTimkiem.setForeground(new java.awt.Color(51, 51, 51));
        btnTimkiem.setText("Tìm");
        btnTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimkiemActionPerformed(evt);
            }
        });

        txtTenMay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenMayActionPerformed(evt);
            }
        });

        txtIDmay.setEditable(false);
        txtIDmay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblSoLuong.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblSoLuong.setForeground(new Color (16,54,103) );
        lblSoLuong.setText("IP");

        lblThongso.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblThongso.setForeground(new Color (16,54,103) );
        lblThongso.setText("Thông số");

        txtThongso.setColumns(20);
        txtThongso.setRows(5);
        jScrollPane2.setViewportView(txtThongso);

        lblTenSP1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTenSP1.setForeground(new Color (16,54,103) );
        lblTenSP1.setText("Tên máy");

        txtLoai1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cboTrangThai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "active", "inactive", "maintenance" }));

        javax.swing.GroupLayout pnlMaytinhLayout = new javax.swing.GroupLayout(pnlMaytinh);
        pnlMaytinh.setLayout(pnlMaytinhLayout);
        pnlMaytinhLayout.setHorizontalGroup(
            pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMaytinhLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMaytinhLayout.createSequentialGroup()
                        .addGroup(pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTenSPTKiem))
                        .addGap(18, 18, 18)
                        .addComponent(btnTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMaytinhLayout.createSequentialGroup()
                        .addGroup(pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMaytinhLayout.createSequentialGroup()
                                .addGroup(pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIDmay, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(203, 203, 203)
                                .addGroup(pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLoaiSP)
                                    .addComponent(txtLoai1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pnlMaytinhLayout.createSequentialGroup()
                                .addGroup(pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtTenMay)
                                    .addComponent(txtVitri, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGia, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTenSP1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(66, 66, 66)
                                .addGroup(pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlMaytinhLayout.createSequentialGroup()
                                        .addGroup(pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTrangthai)
                                            .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(pnlMaytinhLayout.createSequentialGroup()
                                                .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(pnlMaytinhLayout.createSequentialGroup()
                                        .addComponent(txtIP)
                                        .addGap(56, 56, 56)))))
                        .addGroup(pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblThongso, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMaytinhLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(50, 50, 50))))
        );
        pnlMaytinhLayout.setVerticalGroup(
            pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaytinhLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimkiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMaytinhLayout.createSequentialGroup()
                        .addComponent(lblTenSPTKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMaytinhLayout.createSequentialGroup()
                        .addGroup(pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblThongso)
                            .addComponent(lblTenSP))
                        .addGap(8, 8, 8)
                        .addGroup(pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMaytinhLayout.createSequentialGroup()
                                .addGroup(pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIDmay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLoai1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTenSP1)
                                    .addComponent(lblSoLuong))
                                .addGap(19, 19, 19)
                                .addGroup(pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTenMay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMaytinhLayout.createSequentialGroup()
                                        .addComponent(lblGia)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtVitri, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMaytinhLayout.createSequentialGroup()
                                        .addComponent(lblTrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(65, 65, 65)
                                .addGroup(pnlMaytinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnLast)
                                    .addComponent(btnNext)
                                    .addComponent(btnPrev)
                                    .addComponent(btnFirst))
                                .addGap(47, 47, 47))
                            .addGroup(pnlMaytinhLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(pnlMaytinhLayout.createSequentialGroup()
                        .addComponent(pnlButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(85, Short.MAX_VALUE))))
        );

        tblPanelMayTinh.addTab("Máy tính", pnlMaytinh);

        pnlLoaimay.setBackground(new Color (0, 0, 0, 0));

        pnlNhapsolieu.setBackground(new java.awt.Color(255, 255, 255));
        pnlNhapsolieu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblMaNV.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblMaNV.setForeground(new Color (16,54,103));
        lblMaNV.setText("ID");

        txtTenloai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTenloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenloaiActionPerformed(evt);
            }
        });

        lblTenloaiSP.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTenloaiSP.setForeground(new Color (16,54,103));
        lblTenloaiSP.setText("Giá loại máy");

        txtGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaActionPerformed(evt);
            }
        });

        btnThemLoai.setBackground(new Color (24, 71, 133));
        btnThemLoai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemLoai.setForeground(new java.awt.Color(255, 255, 255));
        btnThemLoai.setText("Thêm");
        btnThemLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLoaiActionPerformed(evt);
            }
        });

        btnSuaLoai.setBackground(new Color (24, 71, 133));
        btnSuaLoai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSuaLoai.setForeground(new java.awt.Color(255, 255, 255));
        btnSuaLoai.setText("Sửa");
        btnSuaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaLoaiActionPerformed(evt);
            }
        });

        btnXoaLoai.setBackground(new Color (24, 71, 133));
        btnXoaLoai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaLoai.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaLoai.setText("Xóa");
        btnXoaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLoaiActionPerformed(evt);
            }
        });

        btnLammoiLoai.setBackground(new Color (24, 71, 133));
        btnLammoiLoai.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLammoiLoai.setForeground(new java.awt.Color(255, 255, 255));
        btnLammoiLoai.setText("Làm mới");
        btnLammoiLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiLoaiActionPerformed(evt);
            }
        });

        lblTenloaiSP1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTenloaiSP1.setForeground(new Color (16,54,103));
        lblTenloaiSP1.setText("Trạng thái");

        lblTenloaiSP2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTenloaiSP2.setForeground(new Color (16,54,103));
        lblTenloaiSP2.setText("Mô tả");

        txtMota.setColumns(20);
        txtMota.setRows(5);
        jScrollPane4.setViewportView(txtMota);

        lblMaNV1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblMaNV1.setForeground(new Color (16,54,103));
        lblMaNV1.setText("Tên loại");

        txtIDloaimay.setEditable(false);
        txtIDloaimay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtIDloaimay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDloaimayActionPerformed(evt);
            }
        });

        cboTrangThai2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboTrangThai2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "active", "inactive" }));

        javax.swing.GroupLayout pnlNhapsolieuLayout = new javax.swing.GroupLayout(pnlNhapsolieu);
        pnlNhapsolieu.setLayout(pnlNhapsolieuLayout);
        pnlNhapsolieuLayout.setHorizontalGroup(
            pnlNhapsolieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhapsolieuLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(pnlNhapsolieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboTrangThai2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlNhapsolieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtGia, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTenloaiSP)
                        .addComponent(txtTenloai)
                        .addComponent(lblMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTenloaiSP1)
                        .addComponent(lblMaNV1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane4)
                        .addGroup(pnlNhapsolieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlNhapsolieuLayout.createSequentialGroup()
                                .addComponent(lblTenloaiSP2)
                                .addGap(228, 228, 228))
                            .addGroup(pnlNhapsolieuLayout.createSequentialGroup()
                                .addGroup(pnlNhapsolieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnThemLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnXoaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(pnlNhapsolieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSuaLoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnLammoiLoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(txtIDloaimay, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        pnlNhapsolieuLayout.setVerticalGroup(
            pnlNhapsolieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNhapsolieuLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblMaNV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtIDloaimay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblMaNV1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenloai, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTenloaiSP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTenloaiSP1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboTrangThai2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTenloaiSP2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(pnlNhapsolieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlNhapsolieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnXoaLoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLammoiLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68))
        );

        pnlDanhMucSP.setBackground(new java.awt.Color(255, 255, 255));
        pnlDanhMucSP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DANH SÁCH", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new Color (33, 21, 81))); // NOI18N
        pnlDanhMucSP.setForeground(new Color (33, 21, 81));

        tblLoaimay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblLoaimay.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Tên loại", "Giá loại máy", "Trạng thái", "Mô tả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoaimay.setGridColor(new java.awt.Color(0, 0, 204));
        tblLoaimay.setName(""); // NOI18N
        tblLoaimay.setRowHeight(23);
        tblLoaimay.setSelectionBackground(new Color (24, 116, 180));
        tblLoaimay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaimayMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblLoaimay);

        javax.swing.GroupLayout pnlDanhMucSPLayout = new javax.swing.GroupLayout(pnlDanhMucSP);
        pnlDanhMucSP.setLayout(pnlDanhMucSPLayout);
        pnlDanhMucSPLayout.setHorizontalGroup(
            pnlDanhMucSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhMucSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 791, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDanhMucSPLayout.setVerticalGroup(
            pnlDanhMucSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDanhMucSPLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlLoaimayLayout = new javax.swing.GroupLayout(pnlLoaimay);
        pnlLoaimay.setLayout(pnlLoaimayLayout);
        pnlLoaimayLayout.setHorizontalGroup(
            pnlLoaimayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoaimayLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(pnlNhapsolieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlDanhMucSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlLoaimayLayout.setVerticalGroup(
            pnlLoaimayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoaimayLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlLoaimayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlNhapsolieu, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDanhMucSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
        );

        tblPanelMayTinh.addTab("Loại máy", pnlLoaimay);

        javax.swing.GroupLayout pnlBackgroudFormSPLayout = new javax.swing.GroupLayout(pnlBackgroudFormSP);
        pnlBackgroudFormSP.setLayout(pnlBackgroudFormSPLayout);
        pnlBackgroudFormSPLayout.setHorizontalGroup(
            pnlBackgroudFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroudFormSPLayout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addComponent(tblPanelMayTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 1238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        pnlBackgroudFormSPLayout.setVerticalGroup(
            pnlBackgroudFormSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroudFormSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tblPanelMayTinh)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackgroudFormSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackgroudFormSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblMaytinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMaytinhMouseClicked
        // TODO add your handling code here:=
        int id = tblMaytinh.rowAtPoint(evt.getPoint());
        String masv = tblMaytinh.getValueAt(id, 0).toString();
        Computer cp = cpd.SelectbyID(masv);
        setForm(cp);
    }//GEN-LAST:event_tblMaytinhMouseClicked

    private void txtVitriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVitriActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txtVitriActionPerformed

    private void btnThemSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemSPActionPerformed
        // TODO add your handling code here:
        insert();
    }//GEN-LAST:event_btnThemSPActionPerformed

    private void btnSuaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaSPActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnSuaSPActionPerformed

    private void btnXoaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaSPActionPerformed
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnXoaSPActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        last();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnThemLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLoaiActionPerformed
        // TODO add your handling code here:
        insertLoaiMay();
    }//GEN-LAST:event_btnThemLoaiActionPerformed

    private void btnSuaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaLoaiActionPerformed
        // TODO add your handling code here:
        updateLoaiMay();
    }//GEN-LAST:event_btnSuaLoaiActionPerformed

    private void btnXoaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLoaiActionPerformed
        // TODO add your handling code here:
        deleteLoaiMay();
    }//GEN-LAST:event_btnXoaLoaiActionPerformed

    private void btnLammoiLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiLoaiActionPerformed
        // TODO add your handling code here:
        clearFormLoaiMay();
    }//GEN-LAST:event_btnLammoiLoaiActionPerformed

    private void tblLoaimayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaimayMouseClicked
        // TODO add your handling code here:
        int id = tblLoaimay.rowAtPoint(evt.getPoint());
        String masv = tblLoaimay.getValueAt(id, 0).toString();
        ComputerGroup lspd = this.cpg.SelectbyID(masv);
        setFormLoaiMay(lspd);
    }//GEN-LAST:event_tblLoaimayMouseClicked

    private void txtTimKiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimKiemCaretUpdate
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTimKiemCaretUpdate

    private void btnTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimkiemActionPerformed
        TimKiem();
    }//GEN-LAST:event_btnTimkiemActionPerformed

    private void btnLammoiSP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiSP1ActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnLammoiSP1ActionPerformed

    private void txtTenloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenloaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenloaiActionPerformed

    private void txtGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGiaActionPerformed

    private void txtTenMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenMayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenMayActionPerformed

    private void txtIDloaimayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDloaimayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDloaimayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLammoiLoai;
    private javax.swing.JButton btnLammoiSP1;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSuaLoai;
    private javax.swing.JButton btnSuaSP;
    private javax.swing.JButton btnThemLoai;
    private javax.swing.JButton btnThemSP;
    private javax.swing.JButton btnTimkiem;
    private javax.swing.JButton btnXoaLoai;
    private javax.swing.JButton btnXoaSP;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JComboBox<String> cboTrangThai2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblGia;
    private javax.swing.JLabel lblLoaiSP;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMaNV1;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenSP;
    private javax.swing.JLabel lblTenSP1;
    private javax.swing.JLabel lblTenSPTKiem;
    private javax.swing.JLabel lblTenloaiSP;
    private javax.swing.JLabel lblTenloaiSP1;
    private javax.swing.JLabel lblTenloaiSP2;
    private javax.swing.JLabel lblThongso;
    private javax.swing.JLabel lblTrangthai;
    private javax.swing.JPanel pnlBackgroudFormSP;
    private javax.swing.JPanel pnlButton;
    private javax.swing.JPanel pnlDanhMucSP;
    private javax.swing.JPanel pnlLoaimay;
    private javax.swing.JPanel pnlMaytinh;
    private javax.swing.JPanel pnlNhapsolieu;
    private javax.swing.JTable tblLoaimay;
    private javax.swing.JTable tblMaytinh;
    private javax.swing.JTabbedPane tblPanelMayTinh;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtIDloaimay;
    private javax.swing.JTextField txtIDmay;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextField txtLoai1;
    private javax.swing.JTextArea txtMota;
    private javax.swing.JTextField txtTenMay;
    private javax.swing.JTextField txtTenloai;
    private javax.swing.JTextArea txtThongso;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtVitri;
    // End of variables declaration//GEN-END:variables

    ComputerDao cpd = new ComputerDao();
    ComputerGroupDao cpg = new ComputerGroupDao();

    private void init() {
//        this.setLocationRelativeTo(null);
        fillTableMayTinh();
        fillLoaiMay();
    }

    private void fillTableMayTinh() {
        DefaultTableModel model = (DefaultTableModel) tblMaytinh.getModel();
        model.setRowCount(0);
        try {
            List<Computer> list = cpd.selectAll();
            for (Computer cp : list) {
                Object[] row = {
                    cp.getComputerId(),
                    cp.getGroupId(),
                    cp.getName(),
                    cp.getStatus(),
                    cp.getSpecifications(),
                    cp.getIpAddress(),
                    cp.getPosition()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MessageBoxQLTN.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    private void fillTableTiemKiem() {
        DefaultTableModel model = (DefaultTableModel) tblMaytinh.getModel();
        model.setRowCount(0);
        try {
            String keyWord = txtTimKiem.getText();
            List<Computer> list = cpd.selectByKeyword(keyWord);
//            List<Computer> list = cpd.selectAll();
            for (Computer cp : list) {
                Object[] row = {
                    cp.getComputerId(),
                    cp.getGroupId(),
                    cp.getName(),
                    cp.getStatus(),
                    cp.getSpecifications(),
                    cp.getIpAddress(),
                    cp.getPosition()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MessageBoxQLTN.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    private void setForm(Computer cp) {
        txtIDmay.setText(String.valueOf(cp.getComputerId()));
        txtTenMay.setText(cp.getName());
        txtIP.setText(cp.getIpAddress());
        txtVitri.setText(String.valueOf(cp.getPosition()));
        txtLoai1.setText(String.valueOf(cp.getGroupId()));
        txtThongso.setText(cp.getSpecifications());
        cboTrangThai.setSelectedItem(cp.getStatus());
    }

    private Computer getForm() {
        Computer cd = new Computer();
//        cd.setComputerId(Integer.parseInt(txtIDmay.getText()));
        cd.setGroupId(Integer.parseInt(txtLoai1.getText()));
        cd.setName(txtTenMay.getText());
        cd.setIpAddress(txtIP.getText());
        cd.setPosition(Integer.parseInt(txtVitri.getText()));
        cd.setSpecifications(txtThongso.getText());
        // Lấy trạng thái từ ComboBox an toàn
        Object selectedItem = cboTrangThai.getSelectedItem();
        if (selectedItem != null) {
            cd.setStatus(selectedItem.toString());
        } else {
            cd.setStatus("active"); // Giá trị mặc định
        }
        return cd;
    }

    private Computer getFormUpdate() {
        Computer cd = new Computer();
        cd.setComputerId(Integer.parseInt(txtIDmay.getText()));
        cd.setGroupId(Integer.parseInt(txtLoai1.getText()));
        cd.setName(txtTenMay.getText());
        cd.setIpAddress(txtIP.getText());
        cd.setPosition(Integer.parseInt(txtVitri.getText()));
        cd.setSpecifications(txtThongso.getText());
        // Lấy trạng thái từ ComboBox an toàn
        Object selectedItem = cboTrangThai.getSelectedItem();
        if (selectedItem != null) {
            cd.setStatus(selectedItem.toString());
        } else {
            cd.setStatus("active"); // Giá trị mặc định
        }
        return cd;
    }

    private void insert() {
        Computer cd = getForm();
        try {
            cpd.insert(cd);
            this.fillTableMayTinh();
            MessageBoxQLTN.alert(this, "Thêm mới thành công");
        } catch (Exception e) {
            MessageBoxQLTN.alert(this, "Thêm mới thất bại");
            e.printStackTrace();
        }
    }

    private void update() {
        Computer kh = getFormUpdate();
        try {
            cpd.update(kh);
            this.fillTableMayTinh();
            clearForm();
            MessageBoxQLTN.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MessageBoxQLTN.alert(pnlBackgroudFormSP, "Cập nhật thất bại!");
        }
    }

    private void delete() {
        try {
            String cd = txtIDmay.getText();
            cpd.delete(cd);
            this.fillTableMayTinh();
            this.clearForm();
            MessageBoxQLTN.alert(this, "Xóa thành công!");
        } catch (Exception e) {
            MessageBoxQLTN.alert(this, "Xóa thất bại!");
            e.printStackTrace();
        }
    }

    private void first() {
        this.row = 0;
        this.edit();
        tblMaytinh.setRowSelectionInterval(this.row, this.row);
    }

    private void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
            tblMaytinh.setRowSelectionInterval(this.row, this.row);
        }
    }

    private void next() {
        if (this.row < tblMaytinh.getRowCount() - 1) {
            this.row++;
            this.edit();
            tblMaytinh.setRowSelectionInterval(this.row, this.row);
        }
    }

    private void last() {
        this.row = tblMaytinh.getRowCount() - 1;
        this.edit();
        tblMaytinh.setRowSelectionInterval(this.row, this.row);
    }

    private void clearForm() {
        Computer cd = new Computer();
        this.setForm(cd);
        txtIDmay.setText("");
        txtLoai1.setText("");
        txtVitri.setText("");
        cboTrangThai.setSelectedIndex(0);
        this.row = -1;
    }

    private int row = -1;

    private void edit() {
        String macd = (String) tblMaytinh.getValueAt(this.row, 0);
        Computer cd = cpd.SelectbyID(macd);
        this.setForm(cd);
    }

    private void fillLoaiMay() {
        DefaultTableModel model = (DefaultTableModel) tblLoaimay.getModel();
        model.setRowCount(0);
        try {
            List<ComputerGroup> list = cpg.selectAll();
            for (ComputerGroup lsp : list) {
                Object[] row = {
                    lsp.getGroupId(),
                    lsp.getName(),
                    lsp.getHourlyRate(),
                    lsp.getStatus(),
                    lsp.getDescription(),};
                model.addRow(row);
            }
        } catch (Exception e) {
            MessageBoxQLTN.alert(this, "Lỗi truy vấn dữ liệu");
        }
    }

    private void setFormLoaiMay(ComputerGroup cpg) {
        txtIDloaimay.setText(String.valueOf(cpg.getGroupId()));
        txtTenloai.setText(cpg.getName());
        txtGia.setText(String.valueOf(cpg.getHourlyRate()));
        cboTrangThai2.setSelectedItem(cpg.getStatus());
        txtMota.setText(cpg.getDescription());
    }

    private ComputerGroup getFormLoaiMay() {
        ComputerGroup lsp = new ComputerGroup();
//        lsp.setGroupId(Integer.parseInt(txtIDloaimay.getText()));
        lsp.setName(txtTenloai.getText());
        lsp.setHourlyRate(new BigDecimal(txtGia.getText()));
        // Lấy trạng thái từ ComboBox an toàn
        Object selectedItem = cboTrangThai2.getSelectedItem();
        if (selectedItem != null) {
            lsp.setStatus(selectedItem.toString());
        } else {
            lsp.setStatus("active"); // Giá trị mặc định
        }
        lsp.setDescription(txtMota.getText());
        return lsp;
    }

    private ComputerGroup getFormUpdateGroup() {
        ComputerGroup cd = new ComputerGroup();
        cd.setGroupId(Integer.parseInt(txtIDloaimay.getText()));
        cd.setName(txtTenloai.getText());
        cd.setHourlyRate(new BigDecimal(txtGia.getText()));
        cd.setDescription(txtMota.getText());
        Object selectedItem = cboTrangThai2.getSelectedItem();
        if (selectedItem != null) {
            cd.setStatus(selectedItem.toString());
        } else {
            cd.setStatus("active"); // Giá trị mặc định
        }
        return cd;
    }

    private void insertLoaiMay() {
        ComputerGroup cd = getFormLoaiMay();
        try {
            cpg.insert(cd);
            fillLoaiMay();
            MessageBoxQLTN.alert(this, "Thêm mới thành công");
        } catch (Exception e) {
            MessageBoxQLTN.alert(this, "Thêm mới thất bại");
            e.printStackTrace();
        }
    }

    private void deleteLoaiMay() {
        try {
            String cd = txtIDloaimay.getText();
            cpg.delete(cd);
            fillLoaiMay();
//                    this.clearForm();
            MessageBoxQLTN.alert(this, "Xóa thành công!");
        } catch (Exception e) {
            MessageBoxQLTN.alert(this, "Xóa thất bại!");
            e.printStackTrace();
        }
    }

    private void updateLoaiMay() {
        ComputerGroup kh = getFormUpdateGroup();
        try {
            cpg.update(kh);
            fillLoaiMay();

            MessageBoxQLTN.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MessageBoxQLTN.alert(pnlBackgroudFormSP, "Cập nhật thất bại!");
        }
    }

    private void clearFormLoaiMay() {
        ComputerGroup cd = new ComputerGroup();
        this.setFormLoaiMay(cd);
//        txtTenloai.setText(AuthRoleQLCH.user.getMaNV());
        txtIDloaimay.setText("");
        txtGia.setText("");
        cboTrangThai.setSelectedIndex(0);
        this.row = -1;
    }

    @Override
    public void formRefresh() {
    }

    void TimKiem() {
        this.fillTableTiemKiem();
        this.clearForm();
        this.row = -1;
    }

}
