/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package QLTN.UI;

import QLTN.Dao.CustomerDao;
import QLTN.Entity.Customer;
import QLTN.Utils.Masterfrom;
import QLTN.Utils.MessageBoxQLTN;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import QLTN.Utils.Masterfrom;
import QLTN.Utils.MessageBoxQLTN;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import QLTN.Utils.Masterfrom;
import QLTN.Utils.MessageBoxQLTN;
import java.awt.Color;
import java.awt.Font;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import QLTN.Utils.Masterfrom;
import QLTN.Utils.MessageBoxQLTN;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import QLTN.Utils.Masterfrom;
import QLTN.Utils.MessageBoxQLTN;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import QLTN.Utils.Masterfrom;
import QLTN.Utils.MessageBoxQLTN;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import QLTN.Utils.Masterfrom;
import QLTN.Utils.MessageBoxQLTN;
import java.awt.Color;
import java.awt.Font;
import java.math.BigDecimal;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import QLTN.Utils.Masterfrom;
import QLTN.Utils.MessageBoxQLTN;
import java.awt.Color;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AD
 */


public class CustomerJPanel extends Masterfrom {

    /**
     * Creates new form KhachHangJPanel
     */
    public CustomerJPanel() {
        initComponents();
        init();

        tblKhachHang.getTableHeader().setFont(new Font("Verdana", Font.BOLD, 14));
        tblKhachHang.getTableHeader().setBackground(new Color(24, 71, 133));
        tblKhachHang.getTableHeader().setForeground(new Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlThietlapthongtinKhachhang = new javax.swing.JPanel();
        lblMaKH = new javax.swing.JLabel();
        txtMaKH = new javax.swing.JTextField();
        lblTenKH = new javax.swing.JLabel();
        txtFullname = new javax.swing.JTextField();
        lblSoDT = new javax.swing.JLabel();
        txtSDT = new javax.swing.JTextField();
        lblDiem = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        btnXoaTrang = new javax.swing.JButton();
        btnCapnhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        lblTenKH1 = new javax.swing.JLabel();
        txtMK = new javax.swing.JTextField();
        btnCapnhat1 = new javax.swing.JButton();
        lblDiem1 = new javax.swing.JLabel();
        cboTrangThai = new javax.swing.JComboBox<>();
        txtSoduTK = new javax.swing.JTextField();
        lblDiem2 = new javax.swing.JLabel();
        pnlTableTTKH = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKhachHang = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new javax.swing.JButton();
        lblTimtenKH = new javax.swing.JLabel();

        setBackground(new Color (0, 0, 0, 0));
        setForeground(new Color (16,54,103));

        pnlThietlapthongtinKhachhang.setBackground(new Color (0, 0, 0, 0));
        pnlThietlapthongtinKhachhang.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thiết lập thông tin khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 19), new Color (33, 21, 81))); // NOI18N

        lblMaKH.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblMaKH.setForeground(new Color (16,54,103));
        lblMaKH.setText("ID");

        txtMaKH.setEditable(false);
        txtMaKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblTenKH.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTenKH.setForeground(new Color (16,54,103));
        lblTenKH.setText("Tên Khách hàng");

        txtFullname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblSoDT.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblSoDT.setForeground(new Color (16,54,103));
        lblSoDT.setText("Số điện thoại");

        txtSDT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        lblDiem.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblDiem.setForeground(new Color (16,54,103));
        lblDiem.setText("Username");

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnXoaTrang.setBackground(new Color (24, 71, 133));
        btnXoaTrang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaTrang.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaTrang.setText("Làm mới");
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });

        btnCapnhat.setBackground(new Color (24, 71, 133));
        btnCapnhat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCapnhat.setForeground(new java.awt.Color(255, 255, 255));
        btnCapnhat.setText("Sửa");
        btnCapnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhatActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new Color (24, 71, 133));
        btnXoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        lblTenKH1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblTenKH1.setForeground(new Color (16,54,103));
        lblTenKH1.setText("Mật khẩu");

        txtMK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnCapnhat1.setBackground(new Color (24, 71, 133));
        btnCapnhat1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCapnhat1.setForeground(new java.awt.Color(255, 255, 255));
        btnCapnhat1.setText("Thêm");
        btnCapnhat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapnhat1ActionPerformed(evt);
            }
        });

        lblDiem1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblDiem1.setForeground(new Color (16,54,103));
        lblDiem1.setText("Trạng thái");

        cboTrangThai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "active", "inactive" }));

        txtSoduTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lblDiem2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblDiem2.setForeground(new Color (16,54,103));
        lblDiem2.setText("Số dư tài khoản");

        javax.swing.GroupLayout pnlThietlapthongtinKhachhangLayout = new javax.swing.GroupLayout(pnlThietlapthongtinKhachhang);
        pnlThietlapthongtinKhachhang.setLayout(pnlThietlapthongtinKhachhangLayout);
        pnlThietlapthongtinKhachhangLayout.setHorizontalGroup(
            pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlThietlapthongtinKhachhangLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTenKH)
                    .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMaKH)
                    .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoDT)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblTenKH1)
                        .addComponent(lblDiem))
                    .addComponent(cboTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiem1)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoduTK, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiem2))
                .addGap(111, 111, 111)
                .addGroup(pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCapnhat1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );
        pnlThietlapthongtinKhachhangLayout.setVerticalGroup(
            pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThietlapthongtinKhachhangLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThietlapthongtinKhachhangLayout.createSequentialGroup()
                        .addComponent(btnCapnhat1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCapnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlThietlapthongtinKhachhangLayout.createSequentialGroup()
                            .addGroup(pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDiem)
                                .addComponent(lblDiem2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSoduTK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(lblTenKH1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblDiem1))
                        .addGroup(pnlThietlapthongtinKhachhangLayout.createSequentialGroup()
                            .addComponent(lblMaKH)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblTenKH)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblSoDT))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlThietlapthongtinKhachhangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cboTrangThai)
                    .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(0, 42, Short.MAX_VALUE))
        );

        pnlTableTTKH.setBackground(new Color (0, 0, 0, 0));
        pnlTableTTKH.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách khách hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 19), new Color (33, 21, 81))); // NOI18N

        tblKhachHang.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblKhachHang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên khách hàng", "Tên tài khoản", "Mật khẩu", "Số điện thoại", "Trạng thái", "Số dư tài khoản"
            }
        ));
        tblKhachHang.setRowHeight(23);
        tblKhachHang.setSelectionBackground(new Color (24, 116, 180));
        tblKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhachHangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKhachHang);

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimKiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimKiemCaretUpdate(evt);
            }
        });
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new Color (24, 71, 133));
        btnTimKiem.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        lblTimtenKH.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        lblTimtenKH.setForeground(new Color (16,54,103) );
        lblTimtenKH.setText("Tên khách hàng");

        javax.swing.GroupLayout pnlTableTTKHLayout = new javax.swing.GroupLayout(pnlTableTTKH);
        pnlTableTTKH.setLayout(pnlTableTTKHLayout);
        pnlTableTTKHLayout.setHorizontalGroup(
            pnlTableTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableTTKHLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(pnlTableTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableTTKHLayout.createSequentialGroup()
                        .addComponent(lblTimtenKH)
                        .addGap(26, 26, 26)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(btnTimKiem)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTableTTKHLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        pnlTableTTKHLayout.setVerticalGroup(
            pnlTableTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTableTTKHLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlTableTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTableTTKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblTimtenKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlThietlapthongtinKhachhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTableTTKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(pnlThietlapthongtinKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(pnlTableTTKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSDTActionPerformed

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangActionPerformed
        clearForm();
    }//GEN-LAST:event_btnXoaTrangActionPerformed

    private void btnCapnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhatActionPerformed
        update();
    }//GEN-LAST:event_btnCapnhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhachHangMouseClicked
        int id = tblKhachHang.rowAtPoint(evt.getPoint());
        String masv = tblKhachHang.getValueAt(id, 0).toString();
        Customer ct = ctd.SelectbyID(masv);
        setForm(ct);
        txtMK.setText("");
    }//GEN-LAST:event_tblKhachHangMouseClicked

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        TimKiem();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
//        TimKiem();
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtTimKiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimKiemCaretUpdate
        // TODO add your handling code here:
//        TimKiem();
    }//GEN-LAST:event_txtTimKiemCaretUpdate

    private void btnCapnhat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapnhat1ActionPerformed
        // TODO add your handling code here:
        insert();
    }//GEN-LAST:event_btnCapnhat1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapnhat;
    private javax.swing.JButton btnCapnhat1;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiem;
    private javax.swing.JLabel lblDiem1;
    private javax.swing.JLabel lblDiem2;
    private javax.swing.JLabel lblMaKH;
    private javax.swing.JLabel lblSoDT;
    private javax.swing.JLabel lblTenKH;
    private javax.swing.JLabel lblTenKH1;
    private javax.swing.JLabel lblTimtenKH;
    private javax.swing.JPanel pnlTableTTKH;
    private javax.swing.JPanel pnlThietlapthongtinKhachhang;
    private javax.swing.JTable tblKhachHang;
    private javax.swing.JTextField txtFullname;
    private javax.swing.JTextField txtMK;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtSoduTK;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    CustomerDao ctd = new CustomerDao();
    int row = -1;

    private void init() {
//        this.setLocationRelativeTo(null);
        this.fillTable();
    }

    void fillTable() {
        DefaultTableModel tblModel = (DefaultTableModel) tblKhachHang.getModel();
        tblModel.setRowCount(0);
        try {
            List<Customer> list = ctd.selectAll();
            for (Customer kh : list) {
                Object[] row = {kh.getCustomerId(), kh.getFullname(), kh.getUsername(),
                    "********", kh.getPhone(), kh.getStatus(), kh.getBalance()}; // Ẩn mật khẩu
                tblModel.addRow(row);
            }
        } catch (Exception e) {
            MessageBoxQLTN.alert(this, "Lỗi truy vấn dữ liệu bảng");
            e.printStackTrace();
        }
    }

    void fillTableTiemKiem() {
        DefaultTableModel tblModel = (DefaultTableModel) tblKhachHang.getModel();
        tblModel.setRowCount(0);
        try {
            String keyWord = txtTimKiem.getText();
            List<Customer> list = ctd.selectByKeyword(keyWord);
            for (Customer kh : list) {
                Object[] row = {kh.getCustomerId(), kh.getFullname(), kh.getUsername(),
                    "********", kh.getPhone(), kh.getStatus(), kh.getBalance()}; // Ẩn mật khẩu
                tblModel.addRow(row);
            }
        } catch (Exception e) {
            MessageBoxQLTN.alert(this, "Lỗi truy vấn dữ liệu bảng");
            e.printStackTrace();
        }
    }

    void setForm(Customer kh) {
        txtMaKH.setText(String.valueOf(kh.getCustomerId()));
        txtFullname.setText(kh.getFullname());
        txtUsername.setText(kh.getUsername());
        txtMK.setText(kh.getPasswordHash());
        txtSDT.setText(kh.getPhone());
        cboTrangThai.setSelectedItem(kh.getStatus());
        txtSoduTK.setText(String.valueOf(kh.getBalance()));
    }

    Customer getForm() {
        Customer kh = new Customer();
        kh.setFullname(txtFullname.getText());
        kh.setUsername(txtUsername.getText());
        kh.setPasswordHash(txtMK.getText());
        kh.setPhone(txtSDT.getText());
        // Lấy trạng thái từ ComboBox an toàn
        Object selectedItem = cboTrangThai.getSelectedItem();
        if (selectedItem != null) {
            kh.setStatus(selectedItem.toString());
        } else {
            kh.setStatus("active"); // Giá trị mặc định
        }
        try {
            kh.setBalance(new BigDecimal(txtSoduTK.getText().trim()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Số dư tài khoản không hợp lệ!");
            kh.setBalance(BigDecimal.ZERO);
        }
        return kh;
    }

    Customer getFormUpdate() {
        Customer kh = new Customer();
        kh.setCustomerId(Integer.parseInt(txtMaKH.getText()));
        kh.setFullname(txtFullname.getText());
        kh.setUsername(txtUsername.getText());
        kh.setPasswordHash(txtMK.getText());
        kh.setPhone(txtSDT.getText());
        kh.setStatus((String) cboTrangThai.getSelectedItem());
        try {
            kh.setBalance(new BigDecimal(txtSoduTK.getText().trim()));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Số dư tài khoản không hợp lệ!");
            kh.setBalance(BigDecimal.ZERO);
        }
        return kh;
    }

    void clearForm() {
        this.setForm(new Customer());
        txtMaKH.setText("");
        cboTrangThai.setSelectedIndex(0);
        row = -1;
    }

    void insert() {
        Customer khModel = getForm();
        try {
            ctd.insert(khModel);
            this.fillTable();
            this.clearForm();
            MessageBoxQLTN.alert(this, "Thêm khách hàng thành công");
        } catch (Exception e) {
            MessageBoxQLTN.alert(this, "Lỗi thêm khách hàng");
            e.printStackTrace();
        }
    }

    void update() {
        Customer khModel = getFormUpdate();
        try {
            ctd.update(khModel);
            this.fillTable();
            this.clearForm();
            MessageBoxQLTN.alert(this, "Cập nhật khách hàng thành công");
        } catch (Exception e) {
            MessageBoxQLTN.alert(this, "Lỗi cập nhật khách hàng");
            e.printStackTrace();
        }
    }

    void delete() {
//        if (!AuthRoleQLTN.isManager()) {
//            MessageBoxQLTN.alert(this, "Bạn không có quyền xóa khách hàng");
//        } else {
        if (MessageBoxQLTN.confirm(this, "Bạn có muốn xóa Khách hàng này")) {
            String maKH = txtMaKH.getText();
            try {
                ctd.delete(maKH);
                this.fillTable();
                this.clearForm();
                MessageBoxQLTN.alert(this, "Xóa khách hàng thành công");
            } catch (Exception e) {
                MessageBoxQLTN.alert(this, "Lỗi xóa khách hàng");
                e.printStackTrace();
            }
        }
//        }
    }

    void TimKiem() {
        this.fillTableTiemKiem();
        this.clearForm();
        this.row = -1;
    }

    @Override
    public void formRefresh() {
    }

}
